-- Create foreign key PESSOAS_FK

CREATE TEMPORARY TABLE temp AS
SELECT *
FROM PESSOAS;

DROP TABLE PESSOAS;

CREATE TABLE PESSOAS (
	PESSOA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PESSOA_NOME TEXT NOT NULL,
	PESSOA_IDADE INTEGER,
	PESSOA_CIDADE_ID INTEGER NOT NULL,
	CONSTRAINT PESSOAS_FK FOREIGN KEY (PESSOA_CIDADE_ID) REFERENCES CIDADES(CIDADE_ID) ON DELETE RESTRICT
);

INSERT INTO PESSOAS
SELECT *
FROM temp;

DROP TABLE temp;
