-- Active: 1657137238915@@127.0.0.1@3306
BEGIN TRANSACTION;
DROP TABLE IF EXISTS CIDADES; 
CREATE TABLE CIDADES (
    CIDADE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CIDADE_NOME TEXT NOT NULL
);

DROP TABLE IF EXISTS PESSOAS; 
CREATE TABLE PESSOAS(
    PESSOA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PESSOA_NOME TEXT NOT NULL,
    PESSOA_IDADE INTEGER, 
    PESSOA_CIDADE_ID INTEGER NOT NULL
);

INSERT INTO CIDADES (CIDADE_NOME)
    VALUES 
    ('CAMPO GRANDE'),
    ('BLUMENAU'),
    ('FLORIANOPOLIS'),
    ('SAO PAULO'),
    ('JOINVILLE');


INSERT INTO PESSOAS(PESSOA_NOME,PESSOA_IDADE,PESSOA_CIDADE_ID)
    VALUES
    ('Adriano Machado',47,1),
    ('Adriana',47,1),
    ('Karina',45,5),
    ('TARSIO',51,2),
    ('SAMIR',50,2),
    ('PEDRO',18,3),
    ('Andre',18,3),
    ('Tamires',18,3),
    ('MARIA',22,4),
    ('PATRICIA',14,2),
    ('PATRICIA',18,1);
COMMIT;

-- SELECT * FROM CIDADES;
-- SELECT * FROM PESSOAS; 



