-- Um para Um com Gerente x Departamento
BEGIN TRANSACTION;
DROP TABLE IF EXISTS MUSICXAUTORES;
CREATE TABLE MUSICXAUTORES (
    id Integer Primary Key, 
    musicas_id Integer, 
    autores_id INTEGER, 
    FOREIGN KEY (musicas_id) REFERENCES musicas(id),
    FOREIGN KEY (autores_id) REFERENCES autores(id)
);
INSERT INTO MUSICXAUTORES VALUES(1,1,1);
INSERT INTO MUSICXAUTORES VALUES(2,1,2);
INSERT INTO MUSICXAUTORES VALUES(3,1,3);
INSERT INTO MUSICXAUTORES VALUES(4,2,4);
INSERT INTO MUSICXAUTORES VALUES(5,2,5);
INSERT INTO MUSICXAUTORES VALUES(6,3,6);
COMMIT;