BEGIN TRANSACTION;
DROP TABLE IF EXISTS PESSOAS;
CREATE TABLE PESSOAS (
    id Integer Primary Key, 
    nome Text, 
    cidade_id INTEGER,
    FOREIGN KEY (cidade_id) REFERENCES CIDADES(id)
);
INSERT INTO PESSOAS VALUES(1,'Karina',3);
INSERT INTO PESSOAS VALUES(2,'Adriano',1);
INSERT INTO PESSOAS VALUES(3,'Samir',2);
INSERT INTO PESSOAS VALUES(4,'Carlos',1);
COMMIT;